const clientErrorCodes = Object.freeze({
    BAD_REQUEST:400,
    FORBIDDEN:403,
    UNAUTHORIZED:401,
    NOT_FOUND:404,
    METHOD_NOT_ALLOWED:405,
    NOT_ACCEPTABLE:406,
    REQUEST_TIMEOUT:408,
    CONFLICT:409,
    GONE:410,
    LENGTH_REQUIRED:411,
    PRECONDITION_FAILED:412,
    PAYLOAD_TOO_LARGE:413,
    UNSUPPORTED_MEDIA_TYPE:415,
    EXPECTATION_FAILED:417,
    UNPROCESSABLE_ENTITY:422,
    TOO_MANY_REQUESTS:429,
    REQUEST_HEADER_FIELDS_TOO_LARGE:431,
    UNAVAILABLE_FOR_LEGAL_REASONS:451,
    NETWORK_AUTHENTICATION_REQUIRED:511,
    NETWORK_CONNECT_TIMEOUT_ERROR:599,
});

const serverErrorCodes = Object.freeze({
    INTERNAL_SERVER_ERROR:500,
    NOT_IMPLEMENTED:501,
    BAD_GATEWAY:502,
    SERVICE_UNAVAILABLE:503,
    GATEWAY_TIMEOUT:504,
    HTTP_VERSION_NOT_SUPPORTED:505,
    NETWORK_AUTHENTICATION_REQUIRED:511,
    NETWORK_CONNECT_TIMEOUT_ERROR:599,
});

const SucessCodes = Object.freeze({
    OK:200,
    CREATED:201,
    NO_CONTENT:204,
    ACCEPTED:202,
    RESET_CONTENT:205,
    PARTIAL_CONTENT:206,
    MULTI_STATUS:207,
    ALREADY_REPORTED:208,
});

module.exports = {
    clientErrorCodes,
    serverErrorCodes,
    SucessCodes,
}